### PR TITLE
Add node affinity rules for addons

### PR DESCRIPTION
**Pull request by orangedeng**
Ingress nginx, coredns and kubedns should be deployed into linux worker
node.

Related issue:
https://github.com/rancher/rancher/issues/20805

### CODE REVIEW

**Comment by gitlawr** [comment]
What about Calico deployments and the metrics server?

**Comment by orangedeng** [comment]
Updated

**Comment by orangedeng** [comment]
Updated. After discussed with @gitlawr offline, we don't need to add scheduling rule for calico controller.

**Comment by orangedeng** [comment]
It is the same logic as we have before. We taints the etcd and control plane before so those workload can't be deployed into those nodes.

**Comment by galal-hussein** [comment]
@superseb this shouldn't break the clusters with only controlplane/etcd nodes, because cni will still be deployed on all nodes

**Comment by superseb** [comment]
The value `true` needs to be quoted here, else it will break due to boolean parsing.

**Comment by orangedeng** [comment]
Updated. Using `Exists` instead of `In` to avoid the `true` string value.

**Comment by orangedeng** [comment]
Rebased.

**Comment by alena1108** [comment]
@superseb can you do a final review

**Comment by superseb** [comment]
If there is never a condition where the value is not `true` to change anything on the node regarding these pods, then this works.

**Comment by alena1108** [comment]
@superseb confirmed with @moelsayed and @galal-hussein that node-role.kubernetes.io/worker is never being set to anything but true. So we are good

**Pull request merged**
