### PR TITLE
[2.6] Add November K8s patches

### PR DESCRIPTION
**Pull request by rayandas**
Related: https://github.com/rancher/rancher/issues/35437

Adds:
1.21.7-rancher1-1
1.20.13-rancher1-1

### CODE REVIEW

**Review by kinarashah — DISMISSED** [review]

**Comment by kinarashah** [comment]
@rayandas Please do not merge this yet, this is to coordinate other stuff that's supposed to be released first.

**Comment by rayandas** [comment]
@kinarashah Yeah Denise mentioned that there will be further changes in 2.5 and 2.6 KDM PRs.

**Review by kinarashah — COMMENTED** [review]
we are now ready to bump flannel in these versions, could we bump flannel version for both k8s versions to `v0.15.1`? https://github.com/rancher/kontainer-driver-metadata/pull/736/files

Also more changes went into `dev-v2.6` from separate branch `dev-v2.6-1.22` so this PR will need to be rebased as well.

**Review by ryansann — DISMISSED** [review]
lgtm

**Review by kinarashah — COMMENTED** [review]
I missed mentioning this earlier, but we also have flannel image used for canal - we need to bump that too to `v0.15.1` 
```
 "canalFlannel": "rancher/coreos-flannel:v0.13.0-rancher1", 
 ```

**Comment by rayandas** [comment]
@kinarashah and same goes for 2.5 KDM PR right?

**Comment by kinarashah** [comment]
@rayandas yeah, that's right.

**Comment by rayandas** [comment]
@kinarashah Just another concern, I see `rancher/coreos-flannel` has no `v1.15.1` tag in docker hub but `rancher/mirrored-coreos-flannel` has v1.15.1.
We used `CanalFlannel:              "rancher/coreos-flannel:v0.13.0-rancher1"` in 1.20.13 but `CanalFlannel:              "rancher/mirrored-coreos-flannel:v0.14.0"` in 1.21.7
Do we need to change the CanalFlannel image and version in K8s 1.20.13? or it will be same as `rancher/coreos-flannel:v0.13.0-rancher1`?

**Comment by rayandas** [comment]
@kinarashah fixed

**Review by kinarashah — APPROVED** [review]

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Pull request merged**
