### PR TITLE
[dev-v2.4] Update k8s 1.17.12, 1.18.9 + 1.16.15 ingress

### PR DESCRIPTION
**Pull request by PennyScissors**
Update k8s 1.17.12, 1.18.9
Add v1.16.15-rancher1-2
Update ingress to v0.35.0

### CODE REVIEW

**Review by luthermonson — DISMISSED** [review]

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/28838

**Review by ryansann — APPROVED** [review]
lgtm

**Comment by PennyScissors** [comment]
Added new template `v1.16.15-rancher1-1` with updated ingress

**Review by luthermonson — APPROVED** [review]

**Review by ryansann — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/28576

**Pull request merged**
