### PR TITLE
remove STUBDOMANINS from upstream coredns template

### PR DESCRIPTION
**Pull request by kinarashah**
https://github.com/rancher/rancher/issues/31567

### CODE REVIEW

**Review by StrongMonkey — DISMISSED** [review]

**Comment by StrongMonkey** [comment]
What is this change, Is it from upstream?

**Comment by kinarashah** [comment]
@StrongMonkey it's present in upstream but we removed it in previous templates. `rke up` passed so didn't realize earlier but then pod never becomes ready because the directive is not defined https://github.com/coredns/deployment/commit/f6d0a56b784a5ec48151db33b4d428402b5bd8d1#diff-2895fd208e2af4ff315b7cd959edff39ee8ed4817e93bef867d3496866a13b0bR63

**Comment by kinarashah** [comment]
https://github.com/rancher/rke/pull/2542

**Review by StrongMonkey — APPROVED** [review]
LGTM. Make sure we configured the webhook image that is introduced so it can be applied with system-default-registry.

**Comment by kinarashah** [comment]
Thanks! Merging this so can get 1.21 to test, opened https://github.com/rancher/rancher/issues/32797 to introduce configurable webhook image.

**Pull request merged**
