### PR TITLE
[2.10] Preview 2.10 Release

### PR DESCRIPTION
**Pull request by HarrisonWAffel**
As `release-v2.10` does not yet exist, this PR is being opened to preview the changes for sign off of creation of the `release-v2.10` branch based off of `dev-v2.10`

### CODE REVIEW

**Review by kinarashah — DISMISSED** [review]
Diff has some versions that already have been released, but verified the new oct patch versions (RKE1):  
- v1.28.15, v1.29.10, v1.30.6 and v.131.2 
- new nginx v1.11.3 is used for all oct patches
- default is v1.31.2

**Review by kinarashah — COMMENTED** [review]
@HarrisonWAffel Looks like the tests weren't updated to use `release/v2.10` after the branch was cut. Could we update it now so can confirm everything is OK before releasing? 
https://github.com/rancher/kontainer-driver-metadata/blob/0e217091950e9561b9cb9e1452e25795bce599e2/scripts/fetch-provisioning-tests#L32 
https://github.com/rancher/kontainer-driver-metadata/blob/0e217091950e9561b9cb9e1452e25795bce599e2/scripts/fetch-provisioning-tests#L15 

As a post release step, we would also need to update the branch in validation to release-v2.10 cc @mitulshah-suse @chiukapoor 
https://github.com/rancher/kontainer-driver-metadata/blob/0e217091950e9561b9cb9e1452e25795bce599e2/scripts/validate-ci#L27

**Comment by HarrisonWAffel** [comment]
Provisioning test changes are being handled in https://github.com/rancher/kontainer-driver-metadata/pull/1553

**Review by ShylajaDevadiga — DISMISSED** [review]

**Comment by HarrisonWAffel** [comment]
Closing as we have created the `release-v2.10` branch

**Pull request closed without merging**
