### PR TITLE
Update RKE2 v1.21 to v1.21.1-rc3+rke2r1

### PR DESCRIPTION
**Pull request by nickgerace**
Relevant issue: https://github.com/rancher/rancher/issues/33201

### CODE REVIEW

**Review by dweomer — APPROVED** [review]

**Comment by dweomer** [comment]
(my approval indicates prior discussion, afaik this should be good)

**Review by rmweir — APPROVED** [review]
LGTM

**Review by davidnuzik — APPROVED** [review]
LGTM

**Comment by nickgerace** [comment]
Merging from approval from @davidnuzik.

**Pull request merged**
