### PR TITLE
[v2.8] Add Debug Arg

### PR DESCRIPTION
**Pull request by inichols**
Adds debug argument for k3s and rke2. This was missing, so to enabling debug you had to manually modify or add another config file on downstream clusters.

### CODE REVIEW

**Review by rancher-max — DISMISSED** [review]

**Comment by inichols** [comment]
@rancher-max anything that needs to be done to get this merged? Would love to be able to have debug enabled via rancher

**Review by brandond — DISMISSED** [review]

**Comment by brandond** [comment]
1. Needs to be rebased
2. Needs to be done for dev-v2.9 and dev-v2.10 as well

**Comment by inichols** [comment]
Believe it should all be good!
https://github.com/rancher/kontainer-driver-metadata/pull/1470
https://github.com/rancher/kontainer-driver-metadata/pull/1471

**Review by brandond — DISMISSED** [review]

**Review by ShylajaDevadiga — DISMISSED** [review]

**Comment by brandond** [comment]
@inichols needs a rebase (again), sorry.

**Review by brandond — DISMISSED** [review]

**Review by brandond — APPROVED** [review]

**Pull request merged**
