### PR TITLE
[v2.7] k8s Feb 2024 Patches

### PR DESCRIPTION
**Pull request by krunalhinguu**
Issue: https://github.com/rancher/rancher/issues/44471

- Added Feb patches k8s versions for rke v1.26.14-rancher-1-1 
- Added Feb patches k8s versions for rke v1.27.11-rancher-1-1

### CODE REVIEW

**Comment by kinarashah** [comment]
@HarrisonWAffel This PR is backporting commits from `dev-v2.7` including 1.27 changes so requesting your review as well.

**Review by HarrisonWAffel — COMMENTED** [review]
Looks good, I take it that rke2/k3s `v1.27.11` will be added in another PR?

**Comment by briandowns** [comment]
> Looks good, I take it that rke2/k3s `v1.27.11` will be added in another PR?

It hasn't been communicated to me that it's necessary but I'll follow up and find out.

**Comment by krunalhinguu** [comment]
@HarrisonWAffel yes, that will be handled in another PR, this change is specific to RKE only.

**Review by HarrisonWAffel — APPROVED** [review]

**Pull request merged**
