### PR TITLE
Kubernetes v1.19.1-rancher1-1

### PR DESCRIPTION
**Pull request by Oats87**
https://github.com/rancher/rancher/issues/26717

### CODE REVIEW

**Review by ryansann — DISMISSED** [review]
lgtm

**Review by superseb — CHANGES_REQUESTED** [review]
* Are the images updated according to k8s 1.19 changelog?
* What is the reason for a new canal/calico when the images are the same (I assume the nftables compatibility?)

**Comment by Oats87** [comment]
> * Are the images updated according to k8s 1.19 changelog?

Which images would you expect to see updated?

> * What is the reason for a new canal/calico when the images are the same (I assume the nftables compatibility?)

The reason for the new Calico/Canal is to add the environment variable `FELIX_IPTABLESBACKEND=auto` for `nftables` compatibility.

**Comment by superseb** [comment]
According to the changelog, etcd went to `3.4.9` and CoreDNS went to `1.7.0`, possible other versions changed as well.

**Comment by Oats87** [comment]
> According to the changelog, etcd went to `3.4.9` and CoreDNS went to `1.7.0`, possible other versions changed as well.

Understood, so we are mirroring `kubeadm` build out. I'll work on getting those two images bumped, and analyze for any further images.

**Comment by deniseschannon** [comment]
can you validate that 1.19 has appropriate changes as the 1.18.8 template just got merged? https://github.com/rancher/kontainer-driver-metadata/pull/350#event-3747896422

**Comment by Oats87** [comment]
> can you validate that 1.19 has appropriate changes as the 1.18.8 template just got merged? [#350 (comment)](https://github.com/rancher/kontainer-driver-metadata/pull/350#event-3747896422)

I just had to rebase my changes onto the current dev-v2.5 branch

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
