### PR TITLE
Update maxChannelServerVersion for k3s and rke2

### PR DESCRIPTION
**Pull request by rancher-max**
https://github.com/rancher/rancher/issues/39106

### CODE REVIEW

**Review by kinarashah — COMMENTED** [review]
@rancher-max Do we also need to update it for appDefaults here? 
https://github.com/rancher-max/kontainer-driver-metadata/blob/dev-v2.7/channels-rke2.yaml#L4-L12

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/39106

**Comment by snasovich** [comment]
I'm thinking we may need to bump `maxChannelServerVersion` on ALL previous patches to be able to use them.
Even in the UI there is a checkbox to show previous patches and I don't believe we only want the latest patches to be there for 2.7 release:
image

@rancher-max , could you please test if on this PR's content the previous patches are somehow available even if their `maxChannelServerVersion` are 2.6.99?

On that topic, would it be safer (supported?) to just drop `maxChannelServerVersion` for all versions where it is 2.6.99 currently?

**Comment by rancher-max** [comment]
> @rancher-max , could you please test if on this PR's content the previous patches are somehow available even if their maxChannelServerVersion are 2.6.99?

Yep, only the versions I marked show up whether the checkbox is clicked or not. So those with `maxChannelServerVersion` of 2.6.99 are not showing up.

> On that topic, would it be safer (supported?) to just drop maxChannelServerVersion for all versions where it is 2.6.99 currently?

I am in favor of only bringing the most recent releases forward personally. And actually in this case we would bring forth two sets of releases: August and September (once September is finished being validated and actually gets released).

Let me know what you all prefer! I'm happy to bump everything on this PR if that's the final decision, otherwise this is ready for re-review and can be merged whenever.

image

**Comment by snasovich** [comment]
@rancher-max , thank you for checking this.
Could you please also check if this is UI-only limitation or if you "Edit as YAML" you can specify previous patch and it proceeds to provision?
The answer to this may affect the decision.

**Comment by rancher-max** [comment]
Edit as YAML works fine!
image

**Comment by snasovich** [comment]
@rancher-max , thank you for confirming!

For now, it's fine to proceed to unblock QA (pending @kinarashah 's approval as well) - we can agree what to do with the previous versions once I hear back from @deniseschannon on this.

**Edit:** Confirmed we don't want to go back and update previous versions.

**Review by snasovich — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
