### PR TITLE
[dev v2.9] k8s 1.30

### PR DESCRIPTION
**Pull request by vardhaman22**
issue: https://github.com/rancher/rancher/issues/45089
- added rke2 and k3s may 2024 releases
- added kubernetes v1.30.1 for rke,k3s and rke2
- added calico and canal v3.28.0 with new templates.
- updated kube dns images to v1.23.0 and metrics server to v0.7.1, since there was just the image change in yaml manifest for metrics server i have not updated the template.
- did not bump flannel because it is already at latest.
- bumped ingress nginx to v1.10.1 since it is the latest release but it does not officially support v1.30 [ref](https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#supported-versions-table)
- updated base k3s image to v1.30.1+k3s1 and added yq installation steps in Dockerfile.dapper

### CODE REVIEW

**Comment by kinarashah** [comment]
@vardhaman22 we should still bump ingress nginx to the latest available version upstream as we update all addons to the latest for minor k8s version updates.

**Comment by kinarashah** [comment]
@vardhaman22 Also need to add 1.30 to provisioning-tests, https://github.com/rancher/kontainer-driver-metadata/blob/41e26848850a622810f2ce12eeed35588a1e65de/.drone.yml#L88 for example

**Review by rancher-max — APPROVED** [review]
LGTM for k3s and rke2

**Review by kinarashah — APPROVED** [review]

**Comment by kinarashah** [comment]
@vardhaman22 LGTM, was helpful to have commits separately for review but before merging (after @jiaqiluo's approval) could you please squash commits? Doesn't need to be one just big commit, but 2-3 should suffice for history.

**Review by jiaqiluo — APPROVED** [review]
LGTM!

**Comment by vardhaman22** [comment]
> @vardhaman22 LGTM, was helpful to have commits separately for review but before merging (after @jiaqiluo's approval) could you please squash commits? Doesn't need to be one just big commit, but 2-3 should suffice for history.

done @kinarashah 
verified by :https://github.com/rancher/kontainer-driver-metadata/compare/78d512ce9befc4ab78e21c202adb9487cb303e5f..466570489b170e9f76e09d814357ba7a53f56518
 there are no new changes introduced after rebase.

**Pull request merged**
