### PR TITLE
[dev-2.5] Update rke2 for v1.20.4

### PR DESCRIPTION
**Pull request by brandond**
Took a guess at the minChannelServerVersion, let met know if I need to update.

### CODE REVIEW

**Review by davidnuzik — APPROVED** [review]
LGTM but we need to squash so we have one commit for channels and 1 for go generate

**Comment by davidnuzik** [comment]
Note: This PR is so we can get RKE2 1.20.4+rke2r1 added in prep for our next KDM release before R 2.5.7 release.

**Comment by brandond** [comment]
@davidnuzik we only have two commits at the moment, is there something I need to change?

**Comment by kinarashah** [comment]
@davidnuzik LGTM but unsure what this implies 

> Note: This PR is so we can get RKE2 1.20.4+rke2r1 added in prep for our next KDM release before R 2.5.7 release.

**Review by kinarashah — APPROVED** [review]

**Comment by davidnuzik** [comment]
@kinarashah I was just trying to be informative and indicate the intent of the PR. Sorry for any confusion

**Pull request merged**
