### PR TITLE
[v2.9] Sync changes from dev-v2.8 to dev-v2.9 

### PR DESCRIPTION
**Pull request by kinarashah**
- commits from dev-v2.8 
- resolved conflicts 
- fixed server version for k3s/rke2 and pkg/images 

https://github.com/rancher/rancher/issues/44902

### CODE REVIEW

**Comment by kinarashah** [comment]
Requesting review from @rancher-max to go over server versions for rke2/k3s.

**Review by jiaqiluo — DISMISSED** [review]
Good Job! 
LGTM 💯

**Review by rancher-max — COMMENTED** [review]
This looks like it's missing a few commits from March 28th through today

**Comment by kinarashah** [comment]
@rancher-max @jiaqiluo I rebased on the latest commit to verify and seeing some conflicts again, huh I'll fix and request review later. Apologies for the notifications as I push test commits.

**Pull request closed without merging**
