### PR TITLE
RKE2: Fix repo for cpi chart

### PR DESCRIPTION
**Pull request by vardhaman22**
related issue: https://github.com/rancher/rancher/issues/39462

### CODE REVIEW

**Review by snasovich — APPROVED** [review]
LGTM, but need approval from @briandowns or @brandond as well.

**Review by brandond — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
lgtm. cc @briandowns @rancher-max

**Comment by brandond** [comment]
Does this need to go onto other branches as well?

**Comment by snasovich** [comment]
@brandond , since the linked issue has `2023-Q1-2.7x` milestone that means technically it's for upcoming 2.7.next release. I'm not sure we should rush it into out-of-band December patches release, but backport to `dev-v2.6` seems to be the minimum we want.
Though since it's addressing an obvious typo we can probably include it in upcoming out-of-band releases.

@vardhaman22 , is this the only change done to address https://github.com/rancher/rancher/issues/39462 ?

While at it, would like to relink https://github.com/rancher/rancher/issues/39462#issuecomment-1306433102 for visibility. :)

**Comment by vardhaman22** [comment]
> @brandond , since the linked issue has `2023-Q1-2.7x` milestone that means technically it's for upcoming 2.7.next release. I'm not sure we should rush it into out-of-band December patches release, but backport to `dev-v2.6` seems to be the minimum we want. Though since it's addressing an obvious typo we can probably include it in upcoming out-of-band releases.
> 
> @vardhaman22 , is this the only change done to address [rancher/rancher#39462](https://github.com/rancher/rancher/issues/39462) ?
> 
> While at it, would like to relink [rancher/rancher#39462 (comment)](https://github.com/rancher/rancher/issues/39462#issuecomment-1306433102) for visibility. :)

yes @snasovich this is the only change needed to fix https://github.com/rancher/rancher/issues/39462.

**Pull request merged**
