### PR TITLE
[dev-v2.6] upgrade rke2

### PR DESCRIPTION
**Pull request by galal-hussein**

### CODE REVIEW

**Review by davidnuzik — DISMISSED** [review]
LGTM

**Review by kinarashah — DISMISSED** [review]

**Comment by brandond** [comment]
`&serverArgs-v1` and `&agentArgs-v1` needs to be adjusted to reflect the addition of --kube-proxy-arg now that it's in a static pod.

**Comment by galal-hussein** [comment]
> `&serverArgs-v1` and `&agentArgs-v1` needs to be adjusted to reflect the addition of --kube-proxy-arg now that it's in a static pod.

fixed

**Review by davidnuzik — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by davidnuzik** [comment]
QA mentioned data.json output looks faulty here https://github.com/rancher/kontainer-driver-metadata/pull/597/files#diff-3466043f4e9c80fbf070c00304829621b1a0fb888faf131d1235db2e026c65aaR9383 for v1.21.3+rke2r1 entry. But what's strange is channels yaml LGTM so wonder why `go generate` output is bad here???
thankfully 2.6 is not released yet so not a big issue but I did find this odd. @kinarashah @galal-hussein @brandond

**Comment by davidnuzik** [comment]
@ibuildthecloud any idea why go generate output (data/data.json) in this pr for v1.21.3+rke2r1 entry does not include min/maxChannelServerVersion when channels yaml specifies these? We are perplexed.

**Pull request merged**
