### PR TITLE
[dev-v2.7] Add support to rke for docker 23.0.x

### PR DESCRIPTION
**Pull request by doflamingo721**
Update docker version constraints to include the latest docker `23.0.x` versions.
https://docs.docker.com/engine/release-notes/23.0/

Related issue: 
https://github.com/rancher/rancher/issues/40417
https://github.com/rancher/rancher/issues/40731

### CODE REVIEW

**Comment by steve-todorov** [comment]
@kinarashah Hey, what is the status of this PR? We've been doing some house-keeping and was upgrading to k8s 1.25. However we've encountered https://github.com/rancher/rke/issues/3160 which points towards this PR. Is this the only thing necessary to support Docker 23 or is there anything more needed?

**Review by snasovich — DISMISSED** [review]
LGTM, matches https://github.com/rancher/kontainer-driver-metadata/pull/478
k8s 1.23+ only due to versions formally supported by Rancher 2.7.x / RKE 1.4.x

**Comment by snasovich** [comment]
> @kinarashah Hey, what is the status of this PR? We've been doing some house-keeping and was upgrading to k8s 1.25. However we've encountered [rancher/rke#3160](https://github.com/rancher/rke/issues/3160) which points towards this PR. Is this the only thing necessary to support Docker 23 or is there anything more needed?

@steve-todorov , working on merging these changes for the upcoming RKE 1.4.x release, but not 100% sure yet.
Note that it doesn't look https://github.com/rancher/rke/issues/3160 will automatically get fixed by Docker 23.0 support.

**Comment by steve-todorov** [comment]
@snasovich many thanks for your reply! Looking forward to docker 23 support when it becomes available :)

**Comment by snasovich** [comment]
This will need to be changed to go to `dev-v2.7` as we're now targeting Docker 23.0.x support to align with next feature release for 2.7.x as Rancher-level backend and UI changes as needed and we can't deliver support via KDM update only. https://github.com/rancher/rancher/issues/40731#issuecomment-1515612655

**Review by kinarashah — APPROVED** [review]

**Comment by antoinetran** [comment]
Hi! I understand this is merged in rancher images 2.7.X but I cannot find the starting version where this is fixed? Can I assume this is fixed in [v2.7.3](https://github.com/rancher/rancher/releases/tag/v2.7.3) ?

**Pull request merged**
