### PR TITLE
August Release rke2

### PR DESCRIPTION
**Pull request by nikolaishields**
Refactored to follow the channel pattern established in k3s.

### CODE REVIEW

**Review by rancher-max — DISMISSED** [review]
LGTM! And thank you for refactor 🙌 That should make this a lot clearer/simpler going forward 😌

**Review by rancher-max — DISMISSED** [review]

**Review by rancher-max — APPROVED** [review]

**Review by briandowns — APPROVED** [review]

**Review by dereknola — APPROVED** [review]

**Review by brandond — CHANGES_REQUESTED** [review]
Can you squash this down to just two commits? One for the changes to `channels-rke2.yaml`, and one for the changes to `data.json`? I believe that's what's required for commits to this repo.

**Comment by nikolaishields** [comment]
@brandond It's going to be squash merged anyway so I'm not sure the trouble is warranted.

**Comment by brandond** [comment]
The negotiated process is two commits - one for the channels and one for `go generate`.

**Review by brandond — APPROVED** [review]
LGTM as per the discussion on Slack

**Pull request merged**
