### PR TITLE
December 2022 k3s dev v2.7-1222-patches

### PR DESCRIPTION
**Pull request by nikolaishields**

### CODE REVIEW

**Review by rancher-max — CHANGES_REQUESTED** [review]
We should update the default version at the top of the channels.yaml to the latest v1.22 version, but everything else looks good!

**Review by rancher-max — DISMISSED** [review]

**Comment by brandond** [comment]
I believe we were asked to add 1.25 to this as well?

**Comment by nikolaishields** [comment]
> I believe we were asked to add 1.25 to this as well?
@brandond you might be right, let me double check with the KDM folks.

**Comment by rancher-max** [comment]
> > I believe we were asked to add 1.25 to this as well?
> > @brandond you might be right, let me double check with the KDM folks.

No, 1.25 should be made separately in a PR against just dev-v2.7

**Comment by rancher-max** [comment]
https://github.com/rancher/rancher/issues/39886

**Review by brandond — APPROVED** [review]

**Review by rancher-max — APPROVED** [review]

**Pull request merged**
