### PR TITLE
[dev-v2.5] Remove force_tcp from node-local-dns upstream forward

### PR DESCRIPTION
**Pull request by dkeightley**
Related: https://github.com/rancher/rancher/issues/32180

### CODE REVIEW

**Comment by superseb** [comment]
As this is changing existing deployments, was it verified it doesn't cause interruptions when this is applied?

**Comment by dkeightley** [comment]
I ran through a random-generated lookup (to bypass cache) on a 1s loop, attached are the relevant log lines. During the configmap-reload to remove the `force_tcp` I didn't experience any error or connection issues.

[node-local-remove-tcp.log](https://github.com/rancher/kontainer-driver-metadata/files/6332217/node-local-remove-tcp.log)

**Comment by superseb** [comment]
This was incorporated into https://github.com/rancher/kontainer-driver-metadata/pull/545/ for k8s 1.21, @dkeightley can you confirm this needs to be backported to 2.5?

**Comment by dkeightley** [comment]
Thanks @superseb, I would advocate for a v2.5 backport as we have experienced impact, as it's a minimal change that can revert when the addon job runs it would be good to solve long-term. Upgrades to v2.6 may take some time.

**Comment by dkeightley** [comment]
Closing due to inactivity, it remains in release-v2.5.

**Pull request closed without merging**
